[project]
name = "template-esc-sdk"
version = "1.0.0"
description = "A minimal pulumi-esc-sdk project"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = ["pulumi>=3.142.0", "pulumi-esc-sdk>=0.10.5"]

[dependency-groups]
dev = ["pyright>=1.1.390", "ruff>=0.8.2"]
